{% set name = "arabic_reshaper" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0d9b2a9fa29b5f2c1d705f407adf6ca4242405b9cac0e5cc09e6c4f3f8fb68c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
  run_constrained:
    - fonttools >=4.0

test:
  imports:
    - arabic_reshaper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mpcabd/python-arabic-reshaper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reconstruct Arabic sentences to be used in applications that don't support Arabic
  description: Reconstruct Arabic sentences to be used in applications that don't support Arabic
  doc_url: https://github.com/mpcabd/python-arabic-reshaper
  dev_url: https://github.com/mpcabd/python-arabic-reshaper

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
    - mrakitin
