travis:
  secure:
    BINSTAR_TOKEN: mRBDHADRm2kYLPb0WJMmXvpl5uZ9vfK0tGwUjNILkAlr2JKhV+zVa3wCaEt/WEsHglcnyOSItG/2dd8tBrR4ojiWUh0X619NaX2VB/U3FgOZtSgFd03d4qNZJbbcRWb8m3SNJ5kUoOt+XxtjeyK75eevvkbjIbYjYuD+qOWz9fwV5QV0f7aGQFkyuRwv8qqa3O0q7aDASXQVEqu/u/o9Jji2H+WrTRYCQb3X8gnHGMXCBz5I/7T9jEM++0Yx2KMx1pBKGqg2pZG80ii565vvjJYpvyy0enXgy+/Gu/cj01J7emdzz51zcjWxLY5qWTotGXwYXBiO13BE4+BPNvMIWXp1bnHwhe+uvkIzXTGKb+qFen5mK9ocy7+P57ABml0hd+2vRNG4ptK2bmDIJ7G/TRysHn/q5VPc0pKUtc8J877M3Mxs0cOq6lKwLkr6B1BiyzyhH293ZWU9/gTGGnOEFs/IPr9EyCc2w5+RFwVxFPIrGJWhEedgzh/MwdxABS1zgLX69xF5l+sx1DdcScRUzmFTt5fxCDy09Dt+cWIBGjmkOyTOPdqrMEnHK5ATfXYkM76dKUFDdOuaz++eeIrNlkWoY+xS6MM6mZN1nE+SkNK8KpMwaUZ99j2j40ETlWpw20hjERBLW0lNhU6VoySMPMrZtoMHoi/MxVq2B9QqFIs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
